<a href="https://colab.research.google.com/github/akshithasamudrala9515/TASK_TNSIF_AI-ML/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Pandas**

Pandas Notes
Introduction
Pandas is a powerful Python library for data manipulation & analytics.
2 data structures:

Series → 1D array with any datatype
DataFrame → 2D data structure

Series
A Series is a 1D array of indexed data. It is an object built on top of a numpy array.

In [9]:
import numpy as np
import pandas as pd

s = pd.Series([1, 2, 3, 4, 5, 6])
print(s)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

Inbuilt functions:

s.mean()
s.std()
s.min()
s.max()

Descriptive Statistics
count, mean, std, min, max, quartile values

In [3]:
print(s.describe())
print(s.sum())
print(s.mean())
print(s.std())
print(s.min())
print(s.max())

count    6.000000
mean     3.500000
std      1.870829
min      1.000000
25%      2.250000
50%      3.500000
75%      4.750000
max      6.000000
dtype: float64
21
3.5
1.8708286933869707
1
6

Data Manipulation

s.map(func) – Applies a function to every element in the series (only for Series)
s.apply(func) – Similar to map, but more flexible (works for both Series & DataFrame)
s.sort_values() – Sort series
s.drop(labels) – Drop specified labels from series (not deleted permanently, returns new object)

In [4]:
# Example
s.map(lambda x: x * 2)

0     2
1     4
2     6
3     8
4    10
5    12
dtype: int64

In [5]:
applies = s.apply(lambda x: x ** 2)
print(applies)

0     1
1     4
2     9
3    16
4    25
5    36
dtype: int64

In [6]:
s1 = pd.Series([4, 7, 54, 23, 92, 41])

sorted = s1.sort_values()
print(sorted)

0     4
1     7
3    23
5    41
2    54
4    92
dtype: int64

In [7]:
dropped = s.drop(1)
print(dropped)

0    1
2    3
3    4
4    5
5    6
dtype: int64

Handling Missing Data

s.isnull() → Check for missing values, returns a Series of booleans

In [10]:
s2 = pd.Series([2, 4, 6, np.nan, 7, 0])
print(s2.isnull())

0    False
1    False
2    False
3     True
4    False
5    False
dtype: bool

s.notnull() → Opposite of isnull()

In [12]:
print(s2.notnull())

0     True
1     True
2     True
3    False
4     True
5     True
dtype: bool

s.fillna(value) → Fill missing value with specified value

In [13]:
print(s2.fillna(0))

0    2.0
1    4.0
2    6.0
3    0.0
4    7.0
5    0.0
dtype: float64

s.dropna() → Drops all rows that contain missing values (like None, NaN also drops)

In [14]:
s3 = pd.Series([4, 7, 3, None, 8, 2])
print(s3.dropna())

0    4.0
1    7.0
2    3.0
4    8.0
5    2.0
dtype: float64

**Indexing, Slicing & Filtering**

s.iloc[] – Purely integer-location based indexing.
(+) → Left to Right, (–) → Right to Left

In [15]:
print(s.iloc[2])
print(s.iloc[-2])

3
5

s.loc[] – Label based indexing (only +ve, not -ve)

In [16]:
print(s.loc[2])
print(s.loc[1:2])

3
1    2
2    3
dtype: int64

s[s > n] – Filters & returns elements greater than "n"

In [17]:
greater_num = s[s > 4]
print(greater_num)

4    5
5    6
dtype: int64

**Aggregation**

s.sum() – Sums up the values
s.cumsum() – Cumulative sum

In [18]:
print(s.sum())          # 21
print(s.cumsum())

21
0     1
1     3
2     6
3    10
4    15
5    21
dtype: int64

s.aggregate(func) – Aggregate using one or more operations

In [19]:
print(s.aggregate(['sum', 'min', 'max', 'mean']))

sum     21.0
min      1.0
max      6.0
mean     3.5
dtype: float64

**DataFrames**
df.head() – First 5 items — e.g. (7) → (0–6)
df.tail() – Last 5 items — e.g. (8) → (-1 to -7)

In [28]:
#creation
data = {
    "name": ["akshitha","nikhitha","bhargavi","sindhu","sheela","rohini"],
    "age": [22,20,23,24,30,50],
    "branch": ["CSE","IT","DS","ECE","EEE","MECH"],
    "Address": ["MLG","HYD","MLG","NKT","SEC","JBS"]
}

df = pd.DataFrame(data)
print(df)
df.head()
df.tail(2)

       name  age branch Address
0  akshitha   22    CSE     MLG
1  nikhitha   20     IT     HYD
2  bhargavi   23     DS     MLG
3    sindhu   24    ECE     NKT
4    sheela   30    EEE     SEC
5    rohini   50   MECH     JBS

     name  age branch Address
4  sheela   30    EEE     SEC
5  rohini   50   MECH     JBS

Merge
pythonmerged_df = pd.merge(df1, df2, on='Name')

In [24]:
data1 = {
    "name": [],
    "age": []
}
df1 = pd.DataFrame(data1)

data2 = {
    "name": [],
    "branch": []
}
df2 = pd.DataFrame(data2)

merged = pd.merge(df1, df2, on='name')
print(df.describe())

             age
count   6.000000
mean   28.166667
std    11.214574
min    20.000000
25%    22.250000
50%    23.500000
75%    28.500000
max    50.000000

In [30]:

import pandas as pd
import numpy as np

from google.colab import files
uploaded = files.upload()
df = pd.read_csv(list(uploaded.keys())[0])

print("First 5 rows:")
print(df.head())

print("\nDataset Info:")
print(df.info())

print("\nSummary Statistics:")
print(df.describe())


print("\nMissing Values:")
print(df.isnull().sum())


df = df.fillna(0)


if 'temperature' in df.columns:
    filtered_df = df[df['temperature'] > 10]
    print("\nFiltered Data (Temperature > 30):")
    print(filtered_df)


if 'temperature' in df.columns:
    df['weather_type'] = df['temperature'].apply(
        lambda x: 'Hot' if x >= 30 else 'Normal'
    )


if 'weather_condition' in df.columns:
    group_data = df.groupby('weather_condition')['temperature'].mean()
    print("\nAverage Temperature by Weather Condition:")
    print(group_data)


df.to_csv("processed_data.csv", index=False)


from google.colab import files
files.download("processed_data.csv")

Saving usa_rain_prediction_dataset_2024_2025.csv to usa_rain_prediction_dataset_2024_2025.csv
First 5 rows:
         Date  Location  Temperature   Humidity  Wind Speed  Precipitation  \
0  2024-01-01  New York    87.524795  75.655455   28.379506       0.000000
1  2024-01-02  New York    83.259325  28.712617   12.436433       0.526995
2  2024-01-03  New York    80.943050  64.740043   14.184831       0.916884
3  2024-01-04  New York    78.097552  59.738984   19.444029       0.094134
4  2024-01-05  New York    37.059963  34.766784    3.689661       1.361272

   Cloud Cover     Pressure  Rain Tomorrow
0    69.617966  1026.030278              0
1    41.606048   995.962065              0
2    77.364763   980.796739              1
3    52.541196   979.012163              0
4    85.584000  1031.790859              0

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73100 entries, 0 to 73099
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           73100 non-null  object
 1   Location       73100 non-null  object
 2   Temperature    73100 non-null  float64
 3   Humidity       73100 non-null  float64
 4   Wind Speed     73100 non-null  float64
 5   Precipitation  73100 non-null  float64
 6   Cloud Cover    73100 non-null  float64
 7   Pressure       73100 non-null  float64
 8   Rain Tomorrow  73100 non-null  int64
dtypes: float64(6), int64(1), object(2)
memory usage: 5.0+ MB
None

Summary Statistics:
        Temperature      Humidity    Wind Speed  Precipitation   Cloud Cover  \
count  73100.000000  73100.000000  73100.000000   73100.000000  73100.000000
mean      65.182270     59.875041     15.017946       0.390635     54.942807
std       20.205793     23.066115      8.668729       0.474833     25.982487
min       30.000766     20.000272      0.000712       0.000000     10.000856
25%       47.678968     39.800732      7.485182       0.000000     32.318668
50%       65.294949     59.887840     15.102495       0.196909     55.011121
75%       82.636570     79.835990     22.551794       0.673177     77.412469
max       99.997393     99.999025     29.999017       3.078090     99.998957

           Pressure  Rain Tomorrow
count  73100.000000   73100.000000
mean    1005.176013       0.220410
std       20.203889       0.414526
min      970.000919       0.000000
25%      987.697646       0.000000
50%     1005.284188       0.000000
75%     1022.727410       0.000000
max     1039.999765       1.000000

Missing Values:
Date             0
Location         0
Temperature      0
Humidity         0
Wind Speed       0
Precipitation    0
Cloud Cover      0
Pressure         0
Rain Tomorrow    0
dtype: int64